### ISSUE TITLE
support geyser

### ISSUE THREAD

**Issue by Tem4ig** [GGSkyOne/alternative-authentication#1]
Hello, I own a server and I need geyser support so that players can log in to the server from their phone. Is there a way to add geyser?
Written via Google Translate

**Comment by GGSkyOne** [comment]
Hello, this mod has nothing to do with adding cross-platform support for servers, the only thing it does is replace the authentication servers for Minecraft: Java Edition. You may want to consider other mods or plugins to add Geyser support.

I am closing this issue as I consider it irrelevant.
